### PR TITLE
Add HTC One (M9) control file

### PR DESCRIPTION
**Pull request by tunefish**
I discovered and added the control file for the HTC One M9 to the `control_files.json`.
The control file might also be OS specific (LineageOS 14.1):
`/sys/class/power_supply/battery/charger_control`

I also tested that the control file is working as expected:
```
himaul:/ # cat /sys/class/power_supply/battery/status
Charging
himaul:/ # echo 0 > /sys/class/power_supply/battery/charger_control
himaul:/ # cat /sys/class/power_supply/battery/status
Discharging
himaul:/ # echo 1 > /sys/class/power_supply/battery/charger_control
himaul:/ # cat /sys/class/power_supply/battery/status
Charging
```

Thanks for the work on this great app!

### CODE REVIEW

**Comment by tunefish** [comment]
Update: `/sys/class/power_supply/battery/charger_control` is write-only.
Instead, `/sys/class/power_supply/battery/charging_enabled` can be used on HTC One M9 to check the current charging status.
I added a quick fix for the resulting IndexOutOfBoundsException caused by an empty output due to the missing read permission for the control file. If the read permission is missing the app will always write to the control file, just like with activated `alwaysWrite` option.

**Comment by milux** [comment]
I changed it a little, because if I read it correctly, you got your fix a bit wrong...
And, as you have already noticed: Checking before overwriting is not a mandatory thing. Though it can be useful it certain situations, in other situations it messes up everything.
We should not bind such an implementation detail to a control file. (Rather obvious reason: There might be other devices with the same file, yet different semantics...)
We should better check the file attributes for r/w directly, something that's on the agenda anyway, to make the control files writable for certain devices. Just out of curiosity: What happens if you execute `chmod +r /sys/class/power_supply/battery/charger_control` in su context?

**Comment by tunefish** [comment]
Oh yeah you're right, my bad.
I have already tried granting read permissions to `/sys/class/power_supply/battery/charger_control`, however the file is empy. It seems to be for control purposes only, while the current charging status should be obtained from `/sys/class/power_supply/battery/charging_enabled`.

**Comment by IonutGherman** [comment]
I tried to compile this to work with my HTC One M8 since they share same control files, but I receive an error when I try to build app with Android Studio.
In ShareMethods.kt where `if (output.size() == 0 || output[0] != newState) {` is, the compiler says that 

> Error:(95, 28) Expression 'size' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found

Since I'm not a good programmer, I tried only to warn you about this error.

**Comment by cloves2017** [comment]
Guys thanks for attempting to get this done. I have an HTC m9 and HTC 10 that I would love to get this to work. Is there any additional testing I can help out with?

**Comment by milux** [comment]
I will try to have a look at this asap...

**Comment by xdnax** [comment]
@milux If you do not have already, please join Telegram and message me @xdnax. Me and Sri Harsha want to set up a price group chat so we can chat about issues and such there. I will delete this after I get a response, we weren't sure how else to get in touch. Thanks!

**Comment by cloves2017** [comment]
Fella's I came across this thread on xda. At least one HTC 10 user says has it working (Also works for the pixel) 

It uses:
/sys/class/power_supply/charging_source
/sys/class/power_supply/battery_charging_enabled

https://forum.xda-developers.com/pixel-xl/how-to/guide-limit-battery-charge-level-tasker-t3668059

**Comment by milux** [comment]
@IonutGherman I can't confirm the build problem you were describing, sorry. Build works fine for me here, will remove the "bug" flag.

**Comment by milux** [comment]
@tunefish Can you please check out version 1.1.0 and report back if it's working?

**Comment by milux** [comment]
Assume that this works as intended, closing it for now.

**Pull request closed without merging**
