### PR TITLE
Bengali Translation

### PR DESCRIPTION
**Pull request by AdroitAdorKhan**
I was in a hurry! And, kinda noob with Github stuffs! Which took me long! Sorry for the inconvenience!

### CODE REVIEW

**Comment by milux** [comment]
Oh dear... that's based on some conflicting branch, presumably from @xdnax repo?
I will try to fix this mess asap... but hey, at least it's a PR, thanks @AdroitAdorKhan :wink:

@xdnax @sriharshaarangi If you don't mind, I will take care of this. Might require some special Git moves to be done properly. ^^

**Comment by xdnax** [comment]
@milux I would suggest copying the repo he is creating the request from, retrieve the repo so you have access to it, and just cherry pick his translation commit with credits to him... I believe the keeps ownership and everything in tact as well.

**Comment by xdnax** [comment]
@milux I would suggest copying the repo he is creating the request from, retrieve the repo so you have access to it, and just cherry pick his translation commit with credits to him... I believe the keeps ownership and everything in tact as well.

**Comment by AdroitAdorKhan** [comment]
I'm sorry guys! I will be more careful from now on... ahh! I'm such a stupid! >.<

**Comment by milux** [comment]
@AdroitAdorKhan Calm down, everything is fine. Shouldn't take me much more than 5 minutes. :wink:
@xdnax Yep, I had something like that in mind.

**Comment by AdroitAdorKhan** [comment]
@milux thx buddy! Do u guys have any Telegram or other social group?

**Comment by xdnax** [comment]
@AdroitAdorKhan we only use the XDA thread for public means of discussing the app. There is no telegram group or likewise for users to talk about the app.

**Comment by sriharshaarangi** [comment]
Already added :)

**Pull request closed without merging**
