### PR TITLE
Ensuring write permissions on the charging control file.

### PR DESCRIPTION
**Pull request by Reed97123**
**Phone Tested**:  Nexus 5 with latest LineageOS 14.1

**Issue:**  Every reboot the file "charging_enabled" would be set to permissions 444, so read permissions only.  When BatteryChargeLimit would then attempt to modify the file it would fail.  Shelling in through ADB I found I could alter the permissions to add write permissions with "chmod 644 charging_enabled" and after the modification Battery ChargeLimit would operate correctly.  The correct operation would continue until the phone was rebooted at which point the permissions on the file would revert back to 444.  I could then restore correct operation by performing another chmod command.

I contemplated various methods of keeping the file permissions set to writable including including a chmod in the start-up files or creating a cron job to change it.  Ultimately this would be difficult as any updates in the operating system would most likely obliterate my changes periodically.  The best and lightest weight option seemed to be to insert the chmod command right before BatteryChargeLimit attempted the modification of the file.

I have tested the change by downloading/compiling/loading it on my phone with Android Studio.  With this one modification I am now able to reboot the phone and the application operates perfectly.  I do not anticipate this change will bring any negative effects because if the file is already writable the change will effectively do nothing.  However, for those who have a file that isn't writable, this will allow the application to function properly.

### CODE REVIEW

**Comment by milux** [comment]
Already on our agenda as an urgently required improvement for the near future.

**Comment by milux** [comment]
I checked in a slightly different implementation yesterday, will ship with the next release.

**Comment by Reed97123** [comment]
Looks good.  I see you now execute a chmod u+w on the first time you attempt to write the file.

**Comment by Reed97123** [comment]
Any plans on when this is going to be updated to Google Play?  I'd like to switch back to the official version.

Also, I've noticed something strange.  Sometimes it turns off charging and it stops charging, but other times I see it turned off in the control file, but the battery will continue to charge (even with the new code).  It will eventually reach 100% all the while telling me that charging is disabled.

Have you ever seen this happen on your devices?

**Comment by milux** [comment]
Nope, however one very recent issue (https://github.com/sriharshaarangi/BatteryChargeLimit/issues/99) reported something similar.
It seems that the implementation is sometimes screwed up, and the phone doesn't react to the change as expected...

**Comment by milux** [comment]
It's not just the few more writes, those would not harm anybody indeed.
As far as I can remember, we have seen devices that show strange behavior when writing the control file multiple times in the past.
However, it might be worth a try to enable this as the default behavior.

**Comment by sriharshaarangi** [comment]
Available in the latest update(1.1.1)

**Comment by sriharshaarangi** [comment]
Yes, @milux is right. Just now I have tested on mine, and enabling 'Always write control file' gave uncontrollable behaviour(rapid charge-discharge cycles which definitely panics users). That's the reason we didn't make it default, and it might not be in future.

**Pull request closed without merging**
